# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hosted_url',
            field=models.CharField(default='xxx', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(default='xxxx', max_length=500),
            preserve_default=False,
        ),
    ]
